# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ZUniques-Hackathon-STG-UAEN-02

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Print environment info
        run: |
          node -v
          npm -v
          npm ls --depth=0 || true
        working-directory: ./frontend
      
      - name: Install dependencies
        run: npm install --loglevel verbose
        working-directory: ./frontend
      
      - name: Build project
        run: npm run build
        working-directory: ./frontend
      
      - name: Run tests
        run: npm run test -- --runInBand --verbose
        working-directory: ./frontend


      - name: Zip artifact for deployment
        run: zip -r release.zip .
        working-directory: ./frontend


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ZUniques-Hackathon-STG-UAEN-02'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_89B270B0CBDC4DE4A9D11461DB6BF175 }}
